### ISSUE TITLE
Can't see names of Networks

### ISSUE THREAD

**Issue by koubafire** [nolze/tiny-wifi-analyzer#5]
All names are undefined.

**Comment by nolze** [comment]
Thank you for reporting! Could you provide the following details?

- your macOS version (e.g., 12.7 Monterey)
- the app version (you can check it from "About Tiny Wi-Fi Analyzer" from "Tiny Wi-Fi Analyzer" in the menu bar)

**Comment by koubafire** [comment]
Last version Tiny 0.2.0
macOS Sonoma 14.1

**Comment by Chacha1305Poly20** [comment]
Same. 
Sonoma 14.0 (23A344) 

<img width="928" alt="image" src="https://github.com/nolze/tiny-wifi-analyzer/assets/132871067/d7d96dcd-96ce-44ca-af28-14f7c7cf08be">

**Comment by nolze** [comment]
Thank you for another report.
I have updated an internal library (PyObjC) of the app to the latest. (I hope this resolves the issue, but I haven't identified the cause.)
I appreciate it if anyone could try v0.2.1.

- https://github.com/nolze/tiny-wifi-analyzer/releases/tag/v0.2.1

**Comment by koubafire** [comment]
Still Undefined.

**Comment by nolze** [comment]
I looked into [the similar issues](https://github.com/search?q=sonoma+ssid&type=issues) and found that starting from Sonoma, Location Services permission is required to access Wi-Fi SSIDs.
I'm sorry for the inconvenience, but I've updated the app to request the permission on Sonoma and Later.
I'd appreciate your feedback.

- https://github.com/nolze/tiny-wifi-analyzer/releases/tag/v0.3.0rc1

**Comment by koubafire** [comment]
It  works. I love you :D
