### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by internetztube** [nolze/tiny-wifi-analyzer#6]
Hey!

I recently encountered an issue where my wifi network's performance unexpectedly decreased. In my search for a solution, I discovered your repository. I experimented with several tools, but I found that your solution was immediately effective without any complications. I wanted to express my gratitude for your efforts in creating this tool. It was incredibly helpful!

🎉

**Comment by nolze** [comment]
Thank you for your feedback! Grad to hear that.

**Comment by NicolasCharpentier** [comment]
thank you too @nolze
