### ISSUE TITLE
"Cannot Be Opened Because the Developer Cannot be Verified"

### ISSUE THREAD

**Issue by broofa** [nolze/tiny-wifi-analyzer#7]
**macOS version:**
13.4 (22F66)

**App version (try the latest version if available):**
13.4 (22F66)

**Description:**
I ran into this issue (basically what's [described here](https://www.lifewire.com/fix-developer-cannot-be-verified-error-5183898)) after installing the app.  It wasn't entirely unexpected, but it might be worth mentioning this in the README as something users should expect to have to deal with.

(Thanks for the useful utility, btw!)

**Comment by nolze** [comment]
Thank you for your suggestion! Added [an instruction](https://github.com/nolze/tiny-wifi-analyzer#important-note) to the README from the previous release notes.
